services:
  prometheus:
    image: prom/prometheus:latest
    container_name: cloudops-prometheus

    ports:
      - "9091:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml:ro

    depends_on:
      - alertmanager

    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: cloudops-alertmanager

    ports:
      - "9093:9093"

    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./monitoring/slack_url:/etc/alertmanager/slack_url:ro

    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: cloudops-node-exporter

    ports:
      - "9100:9100"

    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: cloudops-loki

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/local-config.yaml

    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: cloudops-promtail

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./monitoring/promtail.yml:/etc/promtail/config.yml:ro

    command: -config.file=/etc/promtail/config.yml

    depends_on:
      - loki

    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: cloudops-jaeger

    ports:
      - "16686:16686" # Jaeger Web UI & Query API
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver

    environment:
      - COLLECTOR_OTLP_ENABLED=true

    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: cloudops-grafana

    ports:
      - "3002:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer

    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning

    depends_on:
      - prometheus
      - loki
      - jaeger

    restart: unless-stopped

volumes:
  grafana_data:
