services:

  api:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: cloudops-api

    ports:
      - "5000:5000"

    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cloudops

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine

    container_name: cloudops-db

    environment:
      POSTGRES_DB: cloudops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloudops"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: