server {
    listen 80;

    location / {
        proxy_pass http://client:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://api:5000;
    }

    location /health {
        proxy_pass http://api:5000/health;
    }
}